---
- name: Install global npm scripts
  become: true
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - hyperlayout
    - hpm-cli
    - mancy

- name: Install hpm packages
  command: hpm install {{ item }}
  with_items:
    - hyperlayout
    - hyper-startup

- name: Add hack repo
  become: true
  yum_repository:
    name: Copr repo for hack fonts
    description: Some YUM repo
    baseurl: https://copr-be.cloud.fedoraproject.org/results/heliocastro/hack-fonts/fedora-$releasever-$basearch/
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/heliocastro/hack-fonts/pubkey.gpg
    gpgcheck: false

- name: Install hack font
  become: true
  package:
    name: hack-fonts
    state: latest
