---
- name: Copy nginx configs
  copy:
    src: ~/.dotfiles/nginx/etc/nginx/sites-enabled
    dest: /etc/nginx/sites-enabled
    owner: root
    group: root
    mode: u+rw,g+rw,o+r

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Build lounge image
  docker_image:
     path: ~/.dotfiles/server/lounge
     name: lounge
     nocache: true

- name: lounge docker container
  docker_container:
    name: lounge
    image: lounge
    state: started
    ports:
      - 9000:9000
    restart_policy: always
    volumes:
      - /home/al/.thelounge:/home/lounge
    keep_volumes: false
