---
- name: Ensure user has correct shell and group
  become: true
  user:
    name: al
    append: yes
    groups: docker
    shell: /bin/zsh
  meta: reset_connection

- name: be sure libselinux-python are installed
  become: true
  dnf: >
    name=libselinux-python
    state=present
  when: ansible_os_family == 'RedHat'

- name: Download node script (fedora)
  get_url:
    url: https://rpm.nodesource.com/setup_8.x
    dest: /tmp
  when: ansible_os_family == 'RedHat'

- name: Download node script (ubuntu)
  get_url:
    url: https://deb.nodesource.com/setup_8.x
    dest: /tmp
  when: ansible_os_family == 'Debian'

- name: Execute the node script
  become: true
  shell: bash /tmp/setup_8.x

- name: Ensure dependencies are installed
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - stow
    - tmux
    - zsh
    - git
    - nodejs

- name: Check if oh-my-zsh already exists
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh

- name: Install oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: not ohmyzsh.stat.exists

- name: Install global npm scripts
  become: true
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - lana-cli
    - npm-check-updates
    - git-fire

- name: Check if dotfiles already exists
  stat:
    path: ~/.dotfiles
  register: dotfiles

- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: https://github.com/McInkay/dotfiles.git
    dest: ~/.dotfiles
    accept_hostkey: yes
  when: not dotfiles.stat.exists

- name: Mount up device by label
  become: true
  mount:
    path: /home/al/.dotfiles/znc
    src: /home/al/.dotfiles/bin/encfs-wrapper#/home/al/.dotfiles/znc-enc
    fstype: fuse
    state: mounted
    boot: true
    opts: rw,user,auto

- name: Mount up device by label
  become: true
  mount:
    path: /home/al/.dotfiles/thelounge
    src: /home/al/.dotfiles/bin/encfs-wrapper#/home/al/.dotfiles/thelounge-enc
    fstype: fuse
    state: mounted
    boot: true
    opts: rw,user,auto

- name: Install dotfiles npm packages
  npm:
    path: ~/.dotfiles

- name: Set up dotfiles
  shell: stow -d ~/.dotfiles -t ~/ {{ item }}
  with_items:
    - zsh
    - tmux
    - git
    - ssh
    - thelounge
    - znc
